# - alias: Toggle Office Light
  # trigger:
    # platform: event
    # event_type: click
    # event_data:
      # entity_id: binary_sensor.switch_office
      # click_type: single
  # action:
    # service: light.toggle
    # data:
      # entity_id: light.yeelight_color1_34ce008baff3
  # id: d1af737b531c4ac5b7d1f6b95dfca51b
# - alias: Toggle Living Room Light
  # trigger:
    # platform: event
    # event_type: click
    # event_data:
      # entity_id: binary_sensor.switch_livingroom
      # click_type: single
  # action:
    # service: light.toggle
    # data:
      # entity_id: light.yeelight_color1_7811dc6815ae
  # id: a47429ed1c1544fdb4fa67f9fcadec78
# - alias: Toggle Bedroom Light
  # trigger:
    # platform: event
    # event_type: click
    # event_data:
      # entity_id: binary_sensor.switch_bedroom
      # click_type: single
  # action:
    # service: light.toggle
    # data:
      # entity_id: light.yeelight_color1_7811dc68270d
  # id: a9191c68f0cd4f049943b369fcea4e89
# - alias: Toggle Guestroom Light
  # trigger:
    # platform: event
    # event_type: click
    # event_data:
      # entity_id: binary_sensor.switch_guestroom
      # click_type: single
  # action:
    # service: light.toggle
    # data:
      # entity_id: light.yeelight_color1_34ce00900f3e
  # id: dea176169a8545ea81f4f55e6c98913d
# - alias: Toggle Door Light On
  # trigger:
    # platform: state
    # entity_id: binary_sensor.door_window_sensor_entry
    # from: 'off'
    # to: 'on'
  # condition:
    # - condition: state
      # entity_id: sun.sun
      # state: below_horizon
  # action:
    # service: light.turn_on
    # entity_id: light.gateway_light_gateway
    # data:
      # brightness: 255
      # hs_color: [0, 0]
# - alias: Toggle Door Light Off
  # trigger:
    # platform: state
    # entity_id: binary_sensor.door_window_sensor_entry
    # from: 'on'
    # to: 'off'
  # condition:
    # - condition: state
      # entity_id: sun.sun
      # state: below_horizon
  # action:
    # - delay: '00:00:05'
    # - service: light.turn_off
      # entity_id: light.gateway_light_gateway
# - alias: Doorbell
  # trigger:
    # platform: event
    # event_type: click
    # event_data:
      # entity_id: binary_sensor.switch_doorbell
      # click_type: single
  # condition:    
    # condition: or
    # conditions:
    # - condition: state
      # entity_id: device_tracker.majko
      # state: 'home'
    # - condition: state
      # entity_id: device_tracker.baska
      # state: 'home'
  # action:
    # service: xiaomi_aqara.play_ringtone
    # data:
      # gw_mac: 78:11:DC:A4:7E:7E
      # ringtone_id: 10
      # ringtone_vol: 15
  # id: 5921f3a11b554bb298d06b266ce318ef
# - alias: Doorbell Notification
  # trigger:
    # platform: event
    # event_type: click
    # event_data:
      # entity_id: binary_sensor.switch_doorbell
      # click_type: single
  # action:
    # service: notify.html5
    # data:
      # message: Someone's at the door!
      # title: Doorbell
      # target:
      # - Majko
      # - Baska
      # - Majkeey-PC
# - alias: Outside Light On
  # trigger:
    # platform: state
    # entity_id: binary_sensor.motion_sensor_outside
    # to: 'on'
  # condition:
    # condition: state
    # entity_id: sun.sun
    # state: below_horizon
  # action:
    # service: light.turn_on
    # entity_id: light.yeelight_color1_7c49eb12c687
# - alias: Outside Light Off
  # trigger:
    # platform: state
    # entity_id: binary_sensor.motion_sensor_outside
    # to: 'off'
    # for: '00:01:00'
  # action:
    # service: light.turn_off
    # entity_id: light.yeelight_color1_7c49eb12c687
# - alias: Main Bathroom Light On
  # trigger:
    # platform: state
    # entity_id: binary_sensor.motion_sensor_bathroom
    # to: 'on'
  # condition:
    # condition: numeric_state
    # entity_id: sensor.illumination_bathroom
    # below: 15
  # action:
    # service: switch.turn_on
    # entity_id: switch.wall_switch_bathroommain
  # id: ahajdkgkskshahd1548djdhs
# - alias: Main Bathroom Light Off
  # trigger:
    # platform: state
    # entity_id: binary_sensor.motion_sensor_bathroom
    # to: 'off'
  # action:
    # - delay: '00:30:00'
    # - service: switch.turn_off
      # entity_id: switch.wall_switch_bathroommain
  # id: ahektkgovkdk4584kfkdkdkm
# - alias: z800_restart
  # trigger:
    # platform: state
    # entity_id: input_select.majkeeypcoptions
    # to: Restart
  # action:
  # - service: shell_command.restart_z800
  # id: 640ee2fabcf34d63b9928a573a8b501f
# - alias: z800_shutdown
  # trigger:
    # platform: state
    # entity_id: input_select.majkeeypcoptions
    # to: Shutdown
  # action:
  # - service: shell_command.shutdown_z800
  # id: 02bf876d97d642d6a503044625b263c0
# - alias: z800_sleep
  # trigger:
    # platform: state
    # entity_id: input_select.majkeeypcoptions
    # to: Sleep
  # action:
  # - service: shell_command.sleep_z800
  # id: b2021139b5074b988ce1a3a6385779c9
# - alias: z800_hibernate
  # trigger:
    # platform: state
    # entity_id: input_select.majkeeypcoptions
    # to: Hibernate
  # action:
  # - service: shell_command.hibernate_z800
  # id: daa2dc2389d34074b59ceb53f871b1cc
# - alias: z850_restart
  # trigger:
    # platform: state
    # entity_id: input_select.baskapcoptions
    # to: Restart
  # action:
  # - service: shell_command.restart_z850
  # id: bdf65bd5b2824c36b2084f56ada8fb16
# - alias: z850_shutdown
  # trigger:
    # platform: state
    # entity_id: input_select.baskapcoptions
    # to: Shutdown
  # action:
  # - service: shell_command.shutdown_z850
  # id: fd51c647f9994456b65afe03e11fdb7c
# - alias: z850_sleep
  # trigger:
    # platform: state
    # entity_id: input_select.baskapcoptions
    # to: Sleep
  # action:
  # - service: shell_command.sleep_z850
  # id: 2de0785d9aae4766b49d9d20035889b0
# - alias: z850_hibernate
  # trigger:
    # platform: state
    # entity_id: input_select.baskapcoptions
    # to: Hibernate
  # action:
  # - service: shell_command.hibernate_z850
  # id: 9393793e137b4dfa83153fce68bd1f21
# - alias: Entry Door Opened
  # trigger:
    # platform: state
    # entity_id: binary_sensor.door_window_sensor_entry
    # from: 'off'
  # condition:
    # condition: and
    # conditions:
    # - condition: state
      # entity_id: device_tracker.majko
      # state: not_home
    # - condition: state
      # entity_id: device_tracker.baska
      # state: not_home 
  # action:
  # - service: notify.html5
    # data:
      # message: Entry Door opened!
      # title: Door alert
      # target:
      # - Majko
      # - Baska
  # id: 697428c06c77418ea6668fd62db7c69a
# - alias: Living Room Door Opened
  # trigger:
    # platform: state
    # entity_id: binary_sensor.door_window_sensor_livingroom
    # from: 'off'
  # condition:
    # condition: and
    # conditions:
    # - condition: state
      # entity_id: device_tracker.majko
      # state: 'not_home'
    # - condition: state
      # entity_id: device_tracker.baska
      # state: 'not_home'
  # action:
  # - service: notify.html5
    # data:
      # message: Living Room Door opened!
      # title: Door alert
      # target:
      # - Majko
      # - Baska
  # id: faf15ae3b1534874ac6962844f4a235e
# - alias: Pantry Window Opened
  # trigger:
    # platform: state
    # entity_id: binary_sensor.door_window_sensor_pantry
    # from: 'off'
  # condition:
    # condition: and
    # conditions:
    # - condition: state
      # entity_id: device_tracker.majko
      # state: 'not_home'
    # - condition: state
      # entity_id: device_tracker.baska
      # state: 'not_home'
  # action:
  # - service: notify.html5
    # data:
      # message: Pantry Window opened!
      # title: Window alert
      # target:
      # - Majko
      # - Baska
# - alias: Office Window Opened
  # trigger:
    # platform: state
    # entity_id: binary_sensor.door_window_sensor_office
    # from: 'off'
  # condition:
    # condition: and
    # conditions:
    # - condition: state
      # entity_id: device_tracker.majko
      # state: 'not_home'
    # - condition: state
      # entity_id: device_tracker.baska
      # state: 'not_home'
  # action:
  # - service: notify.html5
    # data:
      # message: Office Window opened!
      # title: Window alert
      # target:
      # - Majko
      # - Baska
  # id: caeadc1cadd34331b9e717dc02257548
# - alias: Bathroom Window Opened
  # trigger:
    # platform: state
    # entity_id: binary_sensor.door_window_sensor_bathroom
    # from: 'off'
  # condition:
    # condition: and
    # conditions:
    # - condition: state
      # entity_id: device_tracker.majko
      # state: 'not_home'
    # - condition: state
      # entity_id: device_tracker.baska
      # state: 'not_home'
  # action:
  # - service: notify.html5
    # data:
      # message: Bathroom Window opened!
      # title: Window alert
      # target:
      # - Majko
      # - Baska
  # id: 90f845d122b546e9a1589638bad10723
# - alias: Kitchen Window 1 Opened
  # trigger:
    # platform: state
    # entity_id: binary_sensor.door_window_sensor_kitchen1
    # from: 'off'
  # condition:
    # condition: and
    # conditions:
    # - condition: state
      # entity_id: device_tracker.majko
      # state: 'not_home'
    # - condition: state
      # entity_id: device_tracker.baska
      # state: 'not_home'
  # action:
  # - service: notify.html5
    # data:
      # message: Kitchen Window 1 opened!
      # title: Window alert
      # target:
      # - Majko
      # - Baska
  # id: 37eea1d8007748cb9136a7e78a4de696
# - alias: Kitchen Window 2 Opened
  # trigger:
    # platform: state
    # entity_id: binary_sensor.door_window_sensor_kitchen2
    # from: 'off'
  # condition:
    # condition: and
    # conditions:
    # - condition: state
      # entity_id: device_tracker.majko
      # state: 'not_home'
    # - condition: state
      # entity_id: device_tracker.baska
      # state: 'not_home'
  # action:
  # - service: notify.html5
    # data:
      # message: Kitchen Window 2 opened!
      # title: Window alert
      # target:
      # - Majko
      # - Baska
  # id: a2510684945e4de8b08716c7a10e50be
# - alias: Guest Room Window Opened
  # trigger:
    # platform: state
    # entity_id: binary_sensor.door_window_sensor_guestroom
    # from: 'off'
  # condition:
    # condition: and
    # conditions:
    # - condition: state
      # entity_id: device_tracker.majko
      # state: 'not_home'
    # - condition: state
      # entity_id: device_tracker.baska
      # state: 'not_home'
  # action:
  # - service: notify.html5
    # data:
      # message: Guest Room Window opened!
      # title: Window alert
      # target:
      # - Majko
      # - Baska
  # id: b8e8ebc6171645be963a46ab22034750
# - alias: Tech Room Window Opened
  # trigger:
    # platform: state
    # entity_id: binary_sensor.door_window_sensor_techroom
    # from: 'off'
  # condition:
    # condition: and
    # conditions:
    # - condition: state
      # entity_id: device_tracker.majko
      # state: 'not_home'
    # - condition: state
      # entity_id: device_tracker.baska
      # state: 'not_home'
  # action:
  # - service: notify.html5
    # data:
      # message: Tech Room Window opened!
      # title: Window alert
      # target:
      # - Majko
      # - Baska
  # id: 89ee9776c2ae4eea9682abd926fb9b43
# - alias: Bedroom Window 1 Opened
  # trigger:
    # platform: state
    # entity_id: binary_sensor.door_window_sensor_bedroom1
    # from: 'off'
  # condition:
    # condition: and
    # conditions:
    # - condition: state
      # entity_id: device_tracker.majko
      # state: 'not_home'
    # - condition: state
      # entity_id: device_tracker.baska
      # state: 'not_home'
  # action:
  # - service: notify.html5
    # data:
      # message: Bedroom Window 1 opened!
      # title: Window alert
      # target:
      # - Majko
      # - Baska
  # id: d9903f26b6764397a2eeef5658cdc751
# - alias: Bedroom Window 2 Opened
  # trigger:
    # platform: state
    # entity_id: binary_sensor.door_window_sensor_bedroom2
    # from: 'off'
  # condition:
    # condition: and
    # conditions:
    # - condition: state
      # entity_id: device_tracker.majko
      # state: 'not_home'
    # - condition: state
      # entity_id: device_tracker.baska
      # state: 'not_home'
  # action:
  # - service: notify.html5
    # data:
      # message: Bedroom Window 2 opened!
      # title: Window alert
      # target:
      # - Majko
      # - Baska
  # id: 10dcc8eac90c4a34a048b28346ae0d4d
# - alias: Dog Living Room Light
  # trigger:
    # platform: sun
    # event: sunset
    # offset: '-00:20:00'
  # condition:
    # condition: and
    # conditions:
    # - condition: state
      # entity_id: device_tracker.majko
      # state: 'not_home'
    # - condition: state
      # entity_id: device_tracker.baska
      # state: 'not_home'  
  # action:
    # service: light.turn_on
    # entity_id: light.yeelight_color1_7811dc6815ae
  # id: 11asdsdsdas21dsad31313dwedwdda31aa